/* exam.js - SC-300 practice exam.
   Scenario stems in the item formats Microsoft uses. Every question names the
   module and objective it tests, so misses feed Readiness. Yes/No sets and code
   completions score per part; everything else is all-or-nothing. */

var CASES = {
  northwind: {
    title: 'Case study: Northwind Traders',
    html: '<p><strong>Overview.</strong> Northwind Traders is a retailer headquartered in Montréal with 4,000 employees and 120 stores. It uses Microsoft 365 E5. Its Active Directory forest, <code>northwind.local</code>, synchronizes to Microsoft Entra ID with Entra Connect Sync, and the <code>northwindtraders.com</code> domain is federated with an AD FS farm in the Montréal datacenter.</p>' +
      '<p><strong>Recent changes.</strong></p><ul>' +
      '<li>Northwind acquired Tailspin Toys, which has its own Microsoft Entra tenant with 600 users.</li>' +
      '<li>Northwind acquired Adatum Logistics, whose AD forest has no network connectivity to Northwind’s network.</li>' +
      '<li>A shipping partner, Litware, uses a third-party SAML 2.0 identity provider. The <code>litware.com</code> domain is not verified in any Entra tenant.</li></ul>' +
      '<p><strong>Requirements.</strong></p><ul>' +
      '<li>AD FS must be decommissioned within six months. Users must still be able to sign in if the Montréal datacenter is offline, and leaked credentials must be detected.</li>' +
      '<li>Tailspin employees must appear in Northwind’s tenant as members automatically and lose access when they leave Tailspin.</li>' +
      '<li>Adatum users must be synchronized to Northwind’s tenant with minimal on-premises infrastructure.</li>' +
      '<li>Store kiosks are shared and unmanaged. Sessions must end when the browser closes, and files from SharePoint Online and Exchange Online must not be downloaded to them.</li>' +
      '<li>Litware users must sign in to the shipping portal with their own credentials, must accept an NDA, and their access must expire after 90 days unless renewed.</li>' +
      '<li>Sign-in logs must be retained for two years at the lowest cost, and the security team must query the last 90 days with KQL.</li></ul>'
  }
};

var EXAMQ = [
  /* ---------------- Domain 1 ---------------- */
  { id: 'x01', mod: '01-01', obj: 1, type: 'single',
    stem: 'Contoso has offices in five countries. Local IT staff in each country must reset passwords and manage group membership only for users in their own country. Users’ <em>country</em> attribute is populated from HR. What should you recommend?',
    o: ['Five custom roles, one per country', 'One dynamic administrative unit per country, with Helpdesk Administrator and Groups Administrator scoped to each', 'Five dynamic security groups owned by each country’s IT staff', 'A restricted management administrative unit for each country'], a: 1,
    why: 'Administrative units scope roles to a subset of objects, and a dynamic rule on country keeps membership current. Restricted management AUs protect objects from tenant admins, which is not the requirement.' },
  { id: 'x02', mod: '01-01', obj: 3, type: 'yesno',
    stem: 'Megan holds User Administrator directly. She is also a member of a role-assignable group that holds Helpdesk Administrator, and she is eligible for Exchange Administrator in PIM but has not activated it.',
    s: ['Megan can currently use the permissions of both User Administrator and Helpdesk Administrator.', 'Megan can currently manage Exchange Online settings.', 'A group could be made role-assignable after it was created, if needed.'],
    a: [true, false, false], pm: [['01-01', 3], ['01-01', 3], ['01-01', 0]],
    why: 'Role permissions are the union of active assignments, direct and via group. Eligible roles grant nothing until activated. isAssignableToRole can only be set when the group is created.' },
  { id: 'x03', mod: '01-01', obj: 6, type: 'single',
    stem: 'Non-administrators must not be able to create new Microsoft Entra tenants. Which setting do you change?',
    o: ['Restrict access to Microsoft Entra admin center', 'Restrict non-admin users from creating tenants', 'Users can register applications', 'Guest invite settings'], a: 1,
    why: 'The user setting Restrict non-admin users from creating tenants controls tenant creation. Restricting admin center access only hides the portal.' },
  { id: 'x04', mod: '01-02', obj: 5, type: 'multi', pick: 2,
    stem: 'All users in the Marketing department must receive Microsoft 365 E5 without Viva Engage, automatically, and lose it when they leave the department. Which two actions should you perform? Each correct answer presents part of the solution.',
    o: ['Create a dynamic user group with the rule (user.department -eq "Marketing")', 'Assign E5 to the group with the Viva Engage service plan disabled', 'Assign E5 directly to each Marketing user', 'Nest the Marketing group inside an existing licensed group', 'Create an administrative unit for Marketing'], a: [0, 1],
    why: 'Group-based licensing on a dynamic group adds and removes the licence with the attribute, and disabled plans exclude services. Nested groups do not inherit group-based licences.' },
  { id: 'x05', mod: '01-02', obj: 2, type: 'single',
    stem: 'You create a custom security attribute set named Compliance. A Global Administrator reports that they cannot see the attribute values assigned to users. What should you do?',
    o: ['Nothing: Global Administrators can always see them', 'Assign the Attribute Assignment Reader or Attribute Assignment Administrator role', 'Make the attribute searchable', 'Add the users to an administrative unit'], a: 1,
    why: 'Custom security attributes are not readable by Global Administrators by default; the attribute roles grant access.' },
  { id: 'x06', mod: '01-02', obj: 4, type: 'single',
    stem: 'Corporate Windows 11 laptops are domain-joined to AD DS and must satisfy a Conditional Access policy that requires a Microsoft Entra hybrid joined device. What must be in place?',
    o: ['Entra registration of each device by users', 'Microsoft Entra hybrid join, with device objects synchronized by Entra Connect Sync', 'Cloud Sync with device writeback', 'Intune enrollment only'], a: 1,
    why: 'Hybrid join requires the computer objects to be synchronized, which Connect Sync does and Cloud Sync does not.' },
  { id: 'x07', mod: '01-03', obj: 0, type: 'yesno',
    stem: 'You are configuring External collaboration settings in a Microsoft Entra tenant.',
    s: ['Setting guest user access to "Restricted access" limits guests to their own directory objects.', 'You can configure an allow list and a deny list of domains at the same time.', 'Guest invite settings can restrict invitations to users assigned the Guest Inviter role.'],
    a: [true, false, true], pm: [['01-03', 0], ['01-03', 0], ['01-03', 0]],
    why: 'Restricted access is the most restrictive guest setting. Collaboration restrictions use an allow list or a deny list, not both. Invitations can be limited to specific admin roles such as Guest Inviter.' },
  { id: 'x08', mod: '01-03', obj: 3, type: 'single',
    stem: 'Users from Fabrikam’s Microsoft Entra tenant access apps in your tenant and complete MFA at Fabrikam. Your Conditional Access policy requires MFA and prompts them again. You must remove the second prompt without weakening your policy for other external users. What do you configure?',
    o: ['Exclude guests from the MFA policy', 'An organizational setting for Fabrikam in cross-tenant access settings, with inbound trust for MFA', 'B2B direct connect for Fabrikam', 'The default cross-tenant access settings to trust MFA from all tenants'], a: 1,
    why: 'Per-partner inbound trust accepts Fabrikam’s MFA claims only; changing the default would trust every tenant.' },
  { id: 'x09', mod: '01-03', obj: 4, type: 'order',
    stem: 'You are configuring cross-tenant synchronization from a source tenant to a target tenant. Put the actions in the order Microsoft documents.',
    items: ['In the target tenant: allow users sync into this tenant and enable inbound automatic redemption for the source', 'In the source tenant: enable outbound automatic redemption for the target', 'In the source tenant: create the configuration and test the connection', 'In the source tenant: assign users and groups in scope, then start provisioning'],
    why: 'The target must permit inbound sync first; the source then enables outbound redemption, creates and tests the configuration, scopes it and starts the job.' },
  { id: 'x10', mod: '01-03', obj: 2, type: 'single',
    stem: 'A guest user’s company moved from Google Workspace to Microsoft 365. The guest now cannot sign in to your tenant. They must keep all existing group memberships and app assignments. What do you do?',
    o: ['Delete the guest and send a new invitation', 'Reset redemption status on the guest user', 'Convert the guest to a member user', 'Add Google as an identity provider'], a: 1,
    why: 'Resetting redemption lets the guest redeem with the new account while preserving their object and access.' },
  { id: 'x65', mod: '01-03', obj: 5, type: 'yesno',
    stem: 'You are configuring external identities for partners.',
    s: ['SAML/WS-Fed IdP federation can be configured for a partner domain that is DNS-verified in Microsoft Entra ID.', 'For an Entra-verified partner domain, invitation redemption uses the federated IdP first by default.', 'Cross-tenant synchronization changes an existing B2B user’s userType from Guest to Member by default.'],
    a: [true, false, false], pm: [['01-03', 5], ['01-03', 5], ['01-03', 4]],
    why: 'Federation now supports verified and unverified domains. For verified domains Entra ID stays the primary IdP for redemption unless you change the redemption order. Cross-tenant sync creates new users as Member, but an existing B2B user keeps their userType unless the mapping is set to apply Always.' },
  { id: 'x11', mod: '01-04', obj: 5, type: 'order',
    stem: 'You are migrating from AD FS to cloud authentication. Put the steps in order.',
    items: ['Inventory relying parties with the AD FS application activity report', 'Move relying-party applications to Microsoft Entra enterprise apps', 'Enable password hash synchronization', 'Move pilot groups to cloud authentication with staged rollout', 'Convert the domain from federated to managed', 'Decommission AD FS'],
    why: 'Inventory and move apps first, enable the target method, pilot with staged rollout, convert the domain, then remove AD FS.' },
  { id: 'x12', mod: '01-04', obj: 3, type: 'yesno',
    stem: 'Contoso uses pass-through authentication with a single agent installed on its Entra Connect Sync server.',
    s: ['If that server is offline, users cannot sign in to Microsoft 365 by using PTA.', 'Enabling password hash synchronization alongside PTA allows leaked credentials detection.', 'PTA agents require inbound firewall rules from the internet.'],
    a: [true, true, false], pm: [['01-04', 3], ['01-04', 2], ['01-04', 3]],
    why: 'PTA depends on its agents, so one agent is a single point of failure; PHS enables leaked credential detection; agents use outbound connections only.' },
  { id: 'x13', mod: '01-04', obj: 0, type: 'single',
    stem: 'You plan to change sync filtering on your Entra Connect Sync server and want to test the result with no risk to production and keep a warm standby afterwards. What do you deploy?',
    o: ['A second Connect Sync server in staging mode', 'A Cloud Sync agent', 'A second active Connect Sync server', 'Connect Health for sync'], a: 0,
    why: 'A staging-mode server runs imports and syncs without exporting, so you can inspect results, and it can be promoted if the active server fails.' },
  { id: 'x14', mod: '01-04', obj: 6, type: 'single',
    stem: 'You need email alerts when Entra Connect Sync reports errors such as duplicate UPNs, and reports of failed AD FS sign-ins by IP address. What do you use?',
    o: ['Microsoft Entra Connect Health', 'ID Protection', 'Defender for Cloud Apps', 'A diagnostic setting to Event Hubs'], a: 0,
    why: 'Connect Health provides sync error reports and alerts, and the AD FS risky IP report.' },

  /* ---------------- Domain 2 ---------------- */
  { id: 'x15', mod: '02-01', obj: 1, type: 'yesno',
    stem: 'You are configuring authentication methods for a new tenant.',
    s: ['A Temporary Access Pass can be used to register a passkey without the user ever having a password.', 'Passkey profiles can allow synced passkeys for one group while requiring device-bound passkeys with attestation for another.', 'Managing authentication methods in the legacy MFA service settings is still the recommended approach.'],
    a: [true, true, false], pm: [['02-01', 1], ['02-01', 1], ['02-01', 2]],
    why: 'TAP bootstraps passwordless registration; passkey profiles target groups with different passkey types; method management in legacy MFA and SSPR policies was retired in September 2025.' },
  { id: 'x16', mod: '02-01', obj: 5, type: 'multi', pick: 2,
    stem: 'A synced user’s account is compromised. The attacker must lose access to Microsoft 365 as fast as possible. Which two actions should you perform first? Each correct answer presents part of the solution.',
    o: ['Disable the account in AD DS and in Microsoft Entra ID', 'Revoke the user’s sign-in sessions', 'Remove the user’s licences', 'Delete the user in Microsoft Entra ID', 'Run an access review'], a: [0, 1],
    why: 'Disable in both places (a cloud-only change is overwritten by sync) and revoke refresh tokens and sessions; CAE-capable services then reject existing tokens quickly.' },
  { id: 'x17', mod: '02-01', obj: 3, type: 'single',
    stem: 'SSPR is enabled for all users with one method required. Administrators report that they must register two methods. Why?',
    o: ['SSPR requires two methods for everyone', 'Administrators are always covered by a separate, stricter SSPR policy that requires two methods', 'The registration campaign is enabled', 'Security defaults override SSPR'], a: 1,
    why: 'Administrator accounts always have SSPR enabled under a two-gate policy you cannot weaken.' },
  { id: 'x18', mod: '02-01', obj: 6, type: 'single',
    stem: 'Users must not be able to set passwords containing “Northwind” or store names, both in the cloud and when changing passwords on domain-joined PCs. What do you deploy?',
    o: ['Smart lockout', 'A custom banned password list, plus the password protection proxy and DC agents on-premises', 'Seamless SSO', 'Password writeback'], a: 1,
    why: 'The custom banned list enforces in the cloud; the on-premises agents enforce the same lists on DC password changes.' },
  { id: 'x19', mod: '02-01', obj: 4, type: 'single',
    stem: 'You deploy Windows Hello for Business to hybrid joined devices. Users must access on-premises file shares with SSO, and you do not want to deploy certificates. What do you also configure?',
    o: ['Certificate trust', 'Microsoft Entra Kerberos (cloud Kerberos trust)', 'Seamless SSO', 'Pass-through authentication'], a: 1,
    why: 'Cloud Kerberos trust uses Entra Kerberos to issue partial TGTs and needs no PKI.' },
  { id: 'x20', mod: '02-02', obj: 2, type: 'yesno',
    stem: 'Policy A applies to all users and requires MFA. Policy B applies to the Finance group and requires a compliant device. Policy C blocks sign-ins from a named location called Blocked Countries. All three are enabled.',
    s: ['A Finance user on a compliant device at the office must satisfy MFA and device compliance.', 'A Finance user signing in from a blocked country with MFA and a compliant device is granted access.', 'A user in no group with MFA is granted access from the office.'],
    a: [true, false, true], pm: [['02-02', 2], ['02-02', 2], ['02-02', 1]],
    why: 'All applicable grant controls are enforced together, and block overrides any grant.' },
  { id: 'x21', mod: '02-02', obj: 1, type: 'code',
    stem: 'You create a Conditional Access policy with Microsoft Graph PowerShell to block legacy authentication without affecting users yet. Complete the policy.',
    code: "$p = @{\n  displayName = 'CA001-BlockLegacyAuth'\n  state = '[[0]]'\n  conditions = @{\n    users = @{ includeUsers = @('All'); excludeGroups = @($bg) }\n    applications = @{ includeApplications = @('All') }\n    clientAppTypes = @('exchangeActiveSync', '[[1]]')\n  }\n  grantControls = @{ operator = 'OR'; builtInControls = @('[[2]]') }\n}\nNew-MgIdentityConditionalAccessPolicy -BodyParameter $p",
    blanks: [
      { o: ['enabled', 'enabledForReportingButNotEnforced', 'disabled'], a: 1 },
      { o: ['browser', 'mobileAppsAndDesktopClients', 'other'], a: 2 },
      { o: ['mfa', 'block', 'compliantDevice'], a: 1 }],
    pm: [['02-02', 3], ['02-02', 1], ['02-02', 2]],
    why: 'Report-only is enabledForReportingButNotEnforced; legacy protocols are the exchangeActiveSync and other client app types; the control is block.' },
  { id: 'x22', mod: '02-02', obj: 3, type: 'single',
    stem: 'A user reports AADSTS53003 when opening an app. You want to know which policy blocked the sign-in and why others did not apply, for that exact sign-in. Where do you look?',
    o: ['The What If tool', 'The Conditional Access tab of the sign-in log entry', 'The audit log', 'Identity Secure Score'], a: 1,
    why: 'The sign-in’s Conditional Access tab records each policy’s actual result. What If simulates a hypothetical sign-in.' },
  { id: 'x23', mod: '02-02', obj: 4, type: 'single',
    stem: 'You want to create Microsoft’s recommended policy requiring phishing-resistant MFA for administrators, with the least effort and without affecting sign-ins until you review its impact. What do you do?',
    o: ['Enable security defaults', 'Create the policy from a Conditional Access template and leave it in report-only', 'Enable per-user MFA for administrators', 'Create an authentication context'], a: 1,
    why: 'Templates provide the recommended configuration and default to report-only.' },
  { id: 'x24', mod: '02-02', obj: 1, type: 'single',
    stem: 'Attackers are phishing users with device code sign-in prompts. Users never need device code flow except on meeting-room devices. Which Conditional Access condition do you use to block it?',
    o: ['Client apps: Other clients', 'Authentication flows: device code flow', 'Device platforms: Windows', 'Sign-in risk'], a: 1,
    why: 'The authentication flows condition targets device code flow specifically; exclude the meeting-room devices with a device filter or group.' },
  { id: 'x25', mod: '02-03', obj: 2, type: 'single',
    stem: 'After enabling strict location enforcement for continuous access evaluation, users on a split-tunnel VPN are repeatedly signed out of SharePoint. What is the cause?',
    o: ['Token protection is enabled', 'The IP address SharePoint sees is not in the allowed named locations, although the IP Entra saw was', 'Sign-in frequency is set to every time', 'The users are not licensed for CAE'], a: 1,
    why: 'Strict mode enforces location at the resource; split tunnelling produces a different IP at the resource than at Entra.' },
  { id: 'x26', mod: '02-03', obj: 3, type: 'multi', pick: 2,
    stem: 'One SharePoint site holds merger documents. Opening it must require phishing-resistant MFA; the rest of SharePoint must not change. Which two actions should you perform? Each correct answer presents part of the solution.',
    o: ['Create an authentication context and apply it to the site', 'Create a Conditional Access policy that targets the authentication context and requires the phishing-resistant authentication strength', 'Create a Conditional Access policy for Office 365 SharePoint Online requiring phishing-resistant MFA', 'Configure a protected action', 'Enable app enforced restrictions'], a: [0, 1],
    why: 'Authentication context lets the site request step-up; a policy targeting the context enforces it. Targeting SharePoint Online would affect every site.' },
  { id: 'x27', mod: '02-03', obj: 4, type: 'single',
    stem: 'Administrators must complete phishing-resistant MFA immediately before deleting or updating Conditional Access policies, even in an existing session. What do you configure?',
    o: ['PIM approval for Conditional Access Administrator', 'Protected actions using an authentication context', 'Sign-in frequency every time for all admins', 'A restricted management administrative unit'], a: 1,
    why: 'Protected actions bind an authentication context to specific permissions such as updating CA policies.' },
  { id: 'x28', mod: '02-03', obj: 1, type: 'single',
    stem: 'Global Administrators may sign in only from privileged access workstations. PAWs have extensionAttribute1 set to “PAW” and are Intune compliant. What should the policy use?',
    o: ['Device platforms condition', 'Filter for devices on extensionAttribute1 and isCompliant', 'Named locations', 'Require hybrid joined device'], a: 1,
    why: 'Filter for devices matches device attributes; platform is self-reported and cannot identify specific devices.' },
  { id: 'x29', mod: '02-04', obj: 0, type: 'yesno',
    stem: 'You are migrating risk-based policies before October 1, 2026.',
    s: ['After the retirement, user risk should be enforced with a Conditional Access policy that uses the user risk condition.', 'Microsoft’s documented user risk policy uses the Require risk remediation grant, which also requires an authentication strength.', 'A sign-in risk policy that requires MFA can be satisfied by users who have not registered any MFA method.'],
    a: [true, true, false], pm: [['02-04', 0], ['02-04', 0], ['02-04', 1]],
    why: 'Legacy ID Protection policies have a retirement date of October 1, 2026, with no automatic migration; Conditional Access replaces them. Require risk remediation auto-selects an authentication strength (older items expect password change + MFA with require all). Unregistered users cannot satisfy MFA and are blocked.' },
  { id: 'x30', mod: '02-04', obj: 3, type: 'single',
    stem: 'An investigation confirms that an attacker used Priya’s account. You want the user risk policy to force a secure password change at her next sign-in. What do you do?',
    o: ['Dismiss user risk', 'Confirm user compromised', 'Confirm sign-in safe', 'Delete her risky sign-ins'], a: 1,
    why: 'Confirming compromise sets user risk to high, which the user risk policy then enforces.' },
  { id: 'x31', mod: '02-04', obj: 2, type: 'single',
    stem: 'Users still using SMS for MFA should be prompted at sign-in to set up Microsoft Authenticator, and may postpone it only a limited number of times. What do you configure?',
    o: ['The registration campaign in Authentication methods', 'Security defaults', 'The MFA registration policy with a 14-day grace', 'Report suspicious activity'], a: 0,
    why: 'The registration campaign nudges users to register a stronger method, with limited snoozes.' },
  { id: 'x32', mod: '02-04', obj: 4, type: 'single',
    stem: 'A client secret for a single-tenant app registration was published in a public repository. You must block the service principal from signing in outside your corporate IP ranges. What do you need?',
    o: ['A user risk policy', 'Conditional Access for workload identities with Workload Identities Premium', 'Managed identity conversion', 'Defender for Cloud Apps session policy'], a: 1,
    why: 'CA for workload identities, which needs Workload Identities Premium, can block single-tenant service principals by location or risk.' },
  { id: 'x33', mod: '02-05', obj: 1, type: 'single',
    stem: 'You must give remote staff access to 40 internal web apps, file shares and RDP hosts as quickly as possible, replacing the VPN. Different Conditional Access per app is not required yet. What do you configure?',
    o: ['Application Proxy for each app', 'Private Access with Quick Access', 'Per-app Private Access for each resource', 'Remote networks'], a: 1,
    why: 'Quick Access publishes many FQDN and IP segments in one app and supports non-HTTP protocols. Application Proxy handles web apps only.' },
  { id: 'x34', mod: '02-05', obj: 3, type: 'yesno',
    stem: 'You enable the Microsoft traffic profile in Global Secure Access.',
    s: ['It requires a Microsoft Entra Suite licence.', 'With GSA signaling enabled, sign-in logs keep the user’s original public IP address.', 'A Conditional Access policy can require that Microsoft 365 access comes through a compliant network.'],
    a: [false, true, true], pm: [['02-05', 3], ['02-05', 3], ['02-05', 3]],
    why: 'The Microsoft traffic profile needs only Entra ID P1 or P2. Source IP restoration preserves the original IP. The compliant network condition is available once traffic flows through GSA.' },
  { id: 'x35', mod: '02-05', obj: 0, type: 'yesno',
    stem: 'You are deploying the Global Secure Access client for Windows.',
    s: ['A Microsoft Entra joined 64-bit Windows 11 device can tunnel Microsoft, Internet Access and Private Access traffic.', 'A personal Windows device that is only Microsoft Entra registered can tunnel Internet Access traffic.', 'Azure Virtual Desktop multi-session hosts are supported.'],
    a: [true, false, false], pm: [['02-05', 0], ['02-05', 0], ['02-05', 0]],
    why: 'Joined and hybrid joined devices get every profile. Registered BYOD devices are supported in preview for Private Access traffic only. AVD single-session and Windows 365 are supported; multi-session is not.' },
  { id: 'x36', mod: '02-05', obj: 2, type: 'single',
    stem: 'All internet traffic must block malware and adult categories for every user, while only the Sales department is additionally blocked from social media. How do you configure Internet Access?',
    o: ['One security profile linked by CA to all users', 'Malware and adult categories in the baseline profile; social media in a security profile linked by a CA policy scoped to Sales', 'A Defender for Cloud Apps session policy', 'Named locations for Sales'], a: 1,
    why: 'The baseline profile applies to all traffic without CA; per-group profiles are applied through CA with the GSA security profile session control.' },

  /* ---------------- Domain 3 ---------------- */
  { id: 'x37', mod: '03-01', obj: 0, type: 'single',
    stem: 'A GitHub Actions workflow deploys infrastructure to Azure. Your security team forbids storing secrets in GitHub. What should the workflow authenticate as?',
    o: ['A user account with MFA excluded', 'An app registration or user-assigned managed identity with a federated credential for the repository', 'A system-assigned managed identity', 'A service principal with a client secret stored as a GitHub secret'], a: 1,
    why: 'Workload identity federation exchanges GitHub’s OIDC token for an Entra token; no secret exists.' },
  { id: 'x38', mod: '03-01', obj: 3, type: 'code',
    stem: 'Code on an Azure VM must obtain a token for Azure Storage with the VM’s system-assigned managed identity. Complete the request.',
    code: "$t = Invoke-RestMethod -Headers @{ [[0]] = 'true' } -Uri 'http://[[1]]/metadata/identity/oauth2/token?api-version=2018-02-01&resource=[[2]]'",
    blanks: [
      { o: ['Authorization', 'Metadata', 'x-ms-client-id'], a: 1 },
      { o: ['login.microsoftonline.com', '169.254.169.254', 'management.azure.com'], a: 1 },
      { o: ['https://storage.azure.com/', 'https://graph.microsoft.com/', 'https://vault.azure.net'], a: 0 }],
    pm: [['03-01', 3], ['03-01', 3], ['03-01', 3]],
    why: 'IMDS at 169.254.169.254 requires the Metadata: true header; the resource is the audience of the token you want.' },
  { id: 'x39', mod: '03-01', obj: 1, type: 'multi', pick: 2,
    stem: 'Twenty VMs in a scale set must use one identity to read a Key Vault, and access must be configured before the scale set is deployed. Which two actions should you perform? Each correct answer presents part of the solution.',
    o: ['Create a user-assigned managed identity', 'Grant the identity the Key Vault Secrets User role on the vault', 'Enable a system-assigned identity on each VM', 'Create an app registration with a secret', 'Grant the identity Contributor on the subscription'], a: [0, 1],
    why: 'A user-assigned identity exists before the VMs and can be shared; a data-plane role on the vault grants least privilege.' },
  { id: 'x40', mod: '03-02', obj: 2, type: 'yesno',
    stem: 'You publish an internal IIS app that uses Windows Integrated Authentication through Microsoft Entra Application Proxy.',
    s: ['The private network connector requires inbound port 443 from the internet.', 'With Microsoft Entra ID pre-authentication, Conditional Access applies before the request reaches the server.', 'SSO requires Kerberos constrained delegation from the connector’s computer account to the app’s SPN.'],
    a: [false, true, true], pm: [['03-02', 2], ['03-02', 2], ['03-02', 2]],
    why: 'Connectors are outbound only; Entra pre-authentication enables CA; KCD provides SSO to Windows auth apps.' },
  { id: 'x41', mod: '03-02', obj: 5, type: 'single',
    stem: 'Users must be able to consent only to apps from verified publishers that request User.Read, openid, profile and email. Everything else must go to a review team. Which configuration meets this?',
    o: ['Do not allow user consent; enable the admin consent workflow', 'Allow user consent for verified publishers for selected permissions; classify those permissions as low impact; enable the admin consent workflow', 'Let users consent to all apps; create an app governance policy', 'Enable app instance property lock'], a: 1,
    why: 'Permission classifications define low impact, the user consent setting limits consent to them from verified publishers, and the workflow routes the rest.' },
  { id: 'x42', mod: '03-02', obj: 1, type: 'single',
    stem: 'A support engineer must manage SAML SSO and user assignments for every enterprise app but must not configure Application Proxy. Which role follows least privilege?',
    o: ['Application Administrator', 'Cloud Application Administrator', 'Global Administrator', 'Application Developer'], a: 1,
    why: 'Cloud Application Administrator equals Application Administrator minus Application Proxy.' },
  { id: 'x43', mod: '03-02', obj: 3, type: 'single',
    stem: 'A SaaS app’s SAML SSO stopped working this morning for everyone. Nothing changed in Conditional Access. What is the most likely cause to check first?',
    o: ['The SAML signing certificate expired', 'The users’ licences expired', 'The app is not in a collection', 'User consent was disabled'], a: 0,
    why: 'Signing certificates expire (three years by default); an expiry breaks SSO for all users at once.' },
  { id: 'x44', mod: '03-02', obj: 4, type: 'single',
    stem: 'Users are assigned to an enterprise app through the group All-Sales, which contains a nested group Sales-West. Sales-West members get AADSTS50105. Assignment is required. Why?',
    o: ['Sales-West needs a licence', 'Nested group membership is not expanded for app assignment', 'The app needs an app role', 'Consent was not granted'], a: 1,
    why: 'App assignment applies to direct members of assigned groups only.' },
  { id: 'x45', mod: '03-03', obj: 3, type: 'yesno',
    stem: 'An app registration requests Microsoft Graph Mail.Read as a delegated permission and User.Read.All as an application permission. No consent has been granted.',
    s: ['A user can consent to User.Read.All for themselves.', 'After consent, delegated Mail.Read lets the app read only mailboxes the signed-in user can access.', 'The permissions are recorded on the app registration, but granted permissions attach to the service principal.'],
    a: [false, true, true], pm: [['03-03', 3], ['03-03', 3], ['03-03', 0]],
    why: 'Application permissions always need admin consent. Delegated access is the intersection of the permission and the user’s rights. Requests live on the application object; grants attach to the service principal.' },
  { id: 'x46', mod: '03-03', obj: 4, type: 'single',
    stem: 'Your expenses API must let a partner’s daemon app call it without a user, and you want the permission to appear in the partner’s API permissions list as an application permission. What do you define?',
    o: ['A scope under Expose an API', 'An app role with allowed member types set to Applications', 'An optional claim', 'A redirect URI'], a: 1,
    why: 'App roles allowed for Applications surface to other apps as application permissions.' },
  { id: 'x47', mod: '03-03', obj: 2, type: 'single',
    stem: 'A JavaScript single-page app with no backend needs to sign users in and call Graph. How should you configure authentication on its app registration?',
    o: ['Web platform with a client secret', 'SPA platform redirect URI; authorization code flow with PKCE', 'Enable implicit grant for access tokens', 'Enable allow public client flows'], a: 1,
    why: 'SPAs use auth code with PKCE on the SPA platform; implicit grant is legacy and discouraged.' },
  { id: 'x48', mod: '03-04', obj: 4, type: 'single',
    stem: 'Users on unmanaged devices may view files in any sanctioned cloud app in the browser, but downloads of files labelled Highly Confidential must be blocked. Users must not bypass the control with desktop clients. What do you create in Defender for Cloud Apps?',
    o: ['A file policy only', 'A session policy blocking the downloads, and an access policy blocking native clients', 'An activity policy', 'An app governance policy'], a: 1,
    why: 'Session policies control downloads in the session; an access policy blocks native clients, which cannot be proxied.' },
  { id: 'x49', mod: '03-04', obj: 0, type: 'single',
    stem: 'You need continuous cloud discovery attributed to users and devices on managed Windows endpoints, without deploying a log collector. What do you use?',
    o: ['Snapshot reports', 'Defender for Endpoint integration', 'An app connector', 'Conditional Access app control'], a: 1,
    why: 'Defender for Endpoint feeds discovery continuously with user and device context.' },
  { id: 'x50', mod: '03-04', obj: 5, type: 'single',
    stem: 'You must be alerted to OAuth apps that hold high-privilege Microsoft Graph permissions but have not used them for 90 days, and optionally disable them automatically. What do you configure?',
    o: ['An access review of enterprise apps', 'An app governance policy', 'A cloud discovery anomaly policy', 'Permission classifications'], a: 1,
    why: 'App governance policies evaluate OAuth apps’ permissions and usage and can disable them.' },

  /* ---------------- Domain 4 ---------------- */
  { id: 'x51', mod: '04-01', obj: 2, type: 'yesno',
    stem: 'You create an access package in the Sales catalog containing a group, an enterprise app role and a SharePoint site.',
    s: ['Each resource must be added to the Sales catalog before the package can use it.', 'A policy can require two stages of approval and expire assignments after 90 days.', 'External users can request the package even if the catalog is not enabled for external users, provided the policy allows it.'],
    a: [true, true, false], pm: [['04-01', 1], ['04-01', 2], ['04-01', 1]],
    why: 'Resources are added to the catalog first; policies define approval stages and expiry; a catalog must be enabled for external users for them to request its packages.' },
  { id: 'x52', mod: '04-01', obj: 5, type: 'single',
    stem: 'Partner users were onboarded through access packages. When their last assignment expires, their guest accounts must be blocked and then deleted 30 days later. Where do you configure this?',
    o: ['External collaboration settings', 'Entitlement management settings for the lifecycle of external users', 'An access review of all guests', 'Cross-tenant access settings'], a: 1,
    why: 'Entitlement management settings control blocking and removal for external users it onboarded.' },
  { id: 'x53', mod: '04-01', obj: 4, type: 'single',
    stem: 'All guests must accept an acceptable use policy before accessing any app, on every device they use, and re-accept yearly. What do you configure?',
    o: ['Company branding sign-in text', 'Terms of use with require on every device and expiring consents, enforced by a Conditional Access policy for guests', 'An access package policy for all guests', 'The admin consent workflow'], a: 1,
    why: 'Terms of use supports per-device acceptance and consent expiry and is enforced as a CA grant control.' },
  { id: 'x54', mod: '04-02', obj: 1, type: 'multi', pick: 2,
    stem: 'Managers must review their direct reports’ access to the finance app each quarter. Users whose manager does not respond must lose access, without an administrator applying results. Which two settings do you configure? Each correct answer presents part of the solution.',
    o: ['If reviewers don’t respond: Remove access', 'Auto apply results to resource', 'If reviewers don’t respond: No change', 'Reviewers: group owners', 'Justification required: off'], a: [0, 1],
    why: 'Remove access as the default decision plus auto-apply removes unreviewed users automatically.' },
  { id: 'x55', mod: '04-02', obj: 3, type: 'single',
    stem: 'A one-time guest access review has all decisions recorded, but it does not end for five more days, and auto-apply is off. The CISO wants denied guests removed today. What do you do?',
    o: ['Delete the review', 'Stop the review, then apply results', 'Send reminders', 'Reset decisions'], a: 1,
    why: 'Stopping ends the review; with auto-apply off, you then apply results manually.' },
  { id: 'x56', mod: '04-02', obj: 2, type: 'single',
    stem: 'Auditors want a downloadable report of every decision made in access reviews over the last year, including who decided and why. What do you provide?',
    o: ['Sign-in logs', 'Review history reports', 'PIM resource audit', 'Identity Secure Score'], a: 1,
    why: 'Review history produces downloadable reports of decisions across reviews.' },
  { id: 'x57', mod: '04-03', obj: 0, type: 'code',
    stem: 'Make Alex eligible for Exchange Administrator for 180 days with Microsoft Graph PowerShell. Complete the command.',
    code: "New-MgRoleManagementDirectory[[0]] -Action '[[1]]' -PrincipalId $alex.Id -RoleDefinitionId $role.Id -DirectoryScopeId '/' -Justification 'Migration' -ScheduleInfo @{ StartDateTime = (Get-Date); Expiration = @{ Type = 'afterDuration'; Duration = '[[2]]' } }",
    blanks: [
      { o: ['RoleAssignmentScheduleRequest', 'RoleEligibilityScheduleRequest', 'RoleDefinition'], a: 1 },
      { o: ['selfActivate', 'adminAssign', 'adminRemove'], a: 1 },
      { o: ['P180D', 'PT180H', '180'], a: 0 }],
    pm: [['04-03', 0], ['04-03', 0], ['04-03', 0]],
    why: 'Eligibility uses RoleEligibilityScheduleRequest with adminAssign; durations are ISO 8601 (P180D).' },
  { id: 'x58', mod: '04-03', obj: 2, type: 'single',
    stem: 'On-call engineers need Helpdesk Administrator, User Administrator and Authentication Administrator at the same time, only during their shift, with one activation. What do you implement?',
    o: ['Three eligible role assignments per engineer', 'A role-assignable group holding the three roles, with engineers eligible for membership through PIM for Groups', 'A dynamic group with the three roles', 'An administrative unit'], a: 1,
    why: 'PIM for Groups activates membership once, granting every role assigned to the role-assignable group.' },
  { id: 'x59', mod: '04-03', obj: 5, type: 'yesno',
    stem: 'You are reviewing the design of your emergency access accounts.',
    s: ['They should hold Global Administrator as an eligible assignment in PIM with approval.', 'They should be cloud-only accounts on the .onmicrosoft.com domain.', 'Because of mandatory MFA for admin portals, they need a method such as a FIDO2 passkey registered.'],
    a: [false, true, true], pm: [['04-03', 5], ['04-03', 5], ['04-03', 5]],
    why: 'Emergency accounts hold the role permanently active so they work when PIM or MFA infrastructure is the problem; cloud-only avoids federation dependency; mandatory MFA applies to them.' },
  { id: 'x60', mod: '04-03', obj: 3, type: 'single',
    stem: 'Global Administrator activation requires approval, but no approvers are specified in the role settings. Who can approve requests?',
    o: ['The requestor’s manager', 'Active Privileged Role Administrators and Global Administrators', 'Security Administrators only', 'Nobody; activation is automatic'], a: 1,
    why: 'For Entra roles, active Privileged Role Administrators and Global Administrators are the default approvers. If they all hold the role only as eligible, nobody can approve and the tenant is locked out. Azure resource roles have no default approvers.' },
  { id: 'x64', mod: '04-03', obj: 0, type: 'yesno',
    stem: 'Exchange Administrator activation in PIM requires authentication context c1, which a Conditional Access policy enforces with phishing-resistant MFA.',
    s: ['The Conditional Access policy for c1 should target the Exchange Administrator directory role.', 'If no enabled Conditional Access policy targets c1, PIM still requires MFA on activation.', 'For an Azure resource role that requires approval, Privileged Role Administrators approve by default when no approvers are selected.'],
    a: [false, true, false], pm: [['04-03', 0], ['04-03', 0], ['04-03', 1]],
    why: 'During activation the user does not hold the role yet, so the policy must target all or eligible users. PIM falls back to MFA if no enabled policy targets the context. Azure resource roles have no default approvers; only Entra roles fall back to active Privileged Role and Global Administrators.' },
  { id: 'x61', mod: '04-04', obj: 2, type: 'code',
    stem: 'Find IP addresses that failed sign-in with a bad password for more than ten distinct users in the last day. Complete the query.',
    code: "SigninLogs\n| where TimeGenerated > ago(1d)\n| where ResultType == [[0]]\n| summarize Users = [[1]](UserPrincipalName) by [[2]]\n| where Users > 10",
    blanks: [
      { o: ['0', '50126', '53003'], a: 1 },
      { o: ['count', 'dcount', 'make_set'], a: 1 },
      { o: ['IPAddress', 'AppDisplayName', 'UserPrincipalName'], a: 0 }],
    pm: [['04-04', 2], ['04-04', 2], ['04-04', 2]],
    why: '50126 is invalid username or password; dcount counts distinct users; group by IP to find the spray source.' },
  { id: 'x62', mod: '04-04', obj: 0, type: 'single',
    stem: 'A user was not created in ServiceNow by automatic provisioning, although they are assigned to the app. Which log tells you why?',
    o: ['Sign-in logs', 'Audit logs', 'Provisioning logs', 'Graph activity logs'], a: 2,
    why: 'Provisioning logs record each provisioning step and why an object was skipped or failed.' },
  { id: 'x63', mod: '04-04', obj: 4, type: 'single',
    stem: 'Leadership asks for a single measure of how well the tenant follows Microsoft’s identity recommendations, trended over time, with a list of actions to improve it. What do you show them?',
    o: ['Identity Secure Score', 'The Conditional Access insights workbook', 'PIM alerts', 'Usage & insights'], a: 0,
    why: 'Identity Secure Score measures implementation of identity recommendations and lists improvement actions.' },

  /* ---------------- Case study ---------------- */
  { id: 'c01', mod: '01-04', obj: 5, type: 'yesno', case: 'northwind',
    stem: 'You are planning the AD FS decommissioning for Northwind.',
    s: ['Pass-through authentication meets the requirement that users can sign in when the Montréal datacenter is offline.', 'Staged rollout lets pilot groups use cloud authentication before the northwindtraders.com domain is converted.', 'Password hash synchronization is required to meet the leaked credentials requirement.'],
    a: [false, true, true], pm: [['01-04', 3], ['01-04', 5], ['01-04', 2]],
    why: 'PTA depends on on-premises agents and DCs. Staged rollout pilots cloud authentication while the domain stays federated. Leaked credentials detection needs PHS.' },
  { id: 'c02', mod: '01-03', obj: 4, type: 'multi', pick: 2, case: 'northwind',
    stem: 'You need to meet the Tailspin Toys requirement. Which two actions should you perform? Each correct answer presents part of the solution.',
    o: ['In Tailspin’s tenant, configure cross-tenant synchronization with Northwind as the target', 'In Northwind’s cross-tenant access settings for Tailspin, allow users sync into this tenant', 'In Northwind’s tenant, bulk invite Tailspin users', 'Enable B2B direct connect between the tenants', 'Deploy Cloud Sync in Tailspin’s tenant'], a: [0, 1],
    why: 'Cross-tenant sync runs from the source (Tailspin) and the target (Northwind) must allow inbound sync; users are provisioned as members and deprovisioned when they leave.' },
  { id: 'c03', mod: '01-04', obj: 1, type: 'single', case: 'northwind',
    stem: 'How should you synchronize Adatum Logistics users?',
    o: ['Add Adatum’s forest as a second connector on Northwind’s Connect Sync server', 'Install Microsoft Entra Cloud Sync provisioning agents in Adatum’s forest', 'Configure cross-tenant synchronization', 'Bulk create the users from a CSV export'], a: 1,
    why: 'Cloud Sync agents in the disconnected forest need no line of sight to Northwind’s network and minimal infrastructure.' },
  { id: 'c04', mod: '02-03', obj: 0, type: 'multi', pick: 2, case: 'northwind',
    stem: 'Which two Conditional Access session controls should you use for store kiosks? Each correct answer presents part of the solution.',
    o: ['Persistent browser session: never persistent', 'Use app enforced restrictions', 'Require token protection for sign-in sessions', 'Sign-in frequency: 90 days', 'Customize continuous access evaluation: disable'], a: [0, 1],
    why: 'Never persistent ends the session when the browser closes; app enforced restrictions make SharePoint and Exchange web-only with no download on unmanaged devices.' },
  { id: 'c05', mod: '01-03', obj: 5, type: 'single', case: 'northwind',
    stem: 'How should Litware users sign in to Northwind’s shipping portal with their own credentials?',
    o: ['Google federation', 'SAML/WS-Fed identity provider federation for litware.com', 'Cross-tenant access inbound trust', 'Email one-time passcode'], a: 1,
    why: 'Litware’s IdP is third-party SAML, so SAML/WS-Fed IdP federation is the fit. Because litware.com is not verified in Entra, Litware users sign in at their own IdP after federation.' },
  { id: 'c06', mod: '04-01', obj: 2, type: 'order', case: 'northwind',
    stem: 'You need to grant Litware users access to the shipping portal with 90-day expiry and an NDA. Put the actions in order.',
    items: ['Create a catalog enabled for external users', 'Add the shipping portal enterprise app to the catalog', 'Create an access package containing the app’s user role', 'Add a policy for the Litware connected organisation with 90-day expiry and the NDA terms of use required'],
    why: 'A resource must be in the catalog before a package can use it, and the package exists before its request policy.' },
  { id: 'c07', mod: '04-04', obj: 1, type: 'multi', pick: 2, case: 'northwind',
    stem: 'Which two destinations should the Entra diagnostic setting use to meet the log requirements? Each correct answer presents part of the solution.',
    o: ['A storage account with a two-year retention policy', 'A Log Analytics workspace with 90-day retention', 'An Event Hubs namespace', 'The Entra admin center with P2 retention', 'Microsoft Sentinel only'], a: [0, 1],
    why: 'Storage is the cheapest long-term store; Log Analytics provides the 90 days of KQL.' }
];
